using IPL.Gaming.Common.Models.CosmosDB;
using IPL.Gaming.Common.Models.Repository;
using IPL.Gaming.Database;
using IPL.Gaming.Database.Interfaces;
using IPL.Gaming.MatchSchedule;
using IPL.Gaming.Repository;
using IPL.Gaming.Repository.Interfaces;
using IPL.Gaming.Services;
using IPL.Gaming.Services.Interfaces;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Newtonsoft.Json;
using System.Globalization;

Console.WriteLine("IPL Gaming - Match Schedule Import");
Console.WriteLine("===================================\n");

// Load configuration
var configuration = new ConfigurationBuilder()
    .SetBasePath(Directory.GetCurrentDirectory())
    .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
    .Build();

// Set up dependency injection
var services = new ServiceCollection();

// Register configuration
services.AddSingleton<IConfiguration>(configuration);
var cosmosDbSettings = configuration.GetSection("CosmosDbSettings").Get<CosmosDbSettings>();
services.AddSingleton(cosmosDbSettings);

// Register services
services.AddScoped<ICosmosService, CosmosService>();
services.AddScoped<IMatchRepository, MatchRepository>();
services.AddScoped<IMatchService, MatchService>();

var serviceProvider = services.BuildServiceProvider();

try
{
    // Read the match schedule JSON file
    Console.WriteLine("Reading match-schedule.json...");
    var jsonFilePath = Path.Combine(Directory.GetCurrentDirectory(), "match-schedule.json");
    
    if (!File.Exists(jsonFilePath))
    {
        Console.WriteLine($"Error: match-schedule.json not found at {jsonFilePath}");
        return;
    }

    var jsonContent = File.ReadAllText(jsonFilePath);
    var matchSchedule = JsonConvert.DeserializeObject<MatchScheduleRoot>(jsonContent);

    if (matchSchedule?.Matchsummary == null || !matchSchedule.Matchsummary.Any())
    {
        Console.WriteLine("No matches found in the schedule.");
        return;
    }

    Console.WriteLine($"Found {matchSchedule.Matchsummary.Count} matches in the schedule.\n");

    // Get the match service
    var matchService = serviceProvider.GetRequiredService<IMatchService>();

    int successCount = 0;
    int failureCount = 0;

    // Insert each match
    foreach (var matchItem in matchSchedule.Matchsummary)
    {
        try
        {
            // Map the JSON item to Match entity
            var match = new Match
            {
                // Id will be auto-generated by the service
                MatchDate = DateTime.ParseExact(matchItem.MatchDate, "yyyy-MM-dd", CultureInfo.InvariantCulture),
                MatchName = matchItem.MatchName,
                MatchTime = matchItem.MatchTime,
                GMTMatchTime = matchItem.GMTMatchTime,
                GMTMatchDate = matchItem.GMTMatchDate,
                GMTMatchEndTime = matchItem.GMTMatchEndTime,
                GMTMatchEndDate = matchItem.GMTMatchEndDate,
                FirstBattingTeamID = matchItem.FirstBattingTeamID,
                FirstBattingTeamName = matchItem.FirstBattingTeamName,
                SecondBattingTeamID = matchItem.SecondBattingTeamID,
                SecondBattingTeamName = matchItem.SecondBattingTeamName,
                FirstBattingTeamCode = matchItem.FirstBattingTeamCode,
                SecondBattingTeamCode = matchItem.SecondBattingTeamCode,
                GroundID = matchItem.GroundID,
                GroundName = matchItem.GroundName,
                MatchCommenceStartDate = DateTime.ParseExact(matchItem.MatchCommenceStartDate, "yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture),
                City = matchItem.City,
                HomeTeamID = int.Parse(matchItem.HomeTeamID),
                HomeTeamName = matchItem.HomeTeamName,
                AwayTeamID = int.Parse(matchItem.AwayTeamID),
                AwayTeamName = matchItem.AwayTeamName
            };

            // Insert the match
            var createdMatch = await matchService.CreateMatch(match);
            
            Console.WriteLine($"✓ Inserted: {createdMatch.MatchName} (ID: {createdMatch.Id})");
            successCount++;
        }
        catch (Exception ex)
        {
            Console.WriteLine($"✗ Failed to insert: {matchItem.MatchName}");
            Console.WriteLine($"  Error: {ex.Message}");
            failureCount++;
        }
    }

    // Summary
    Console.WriteLine($"\n===================================");
    Console.WriteLine($"Import completed!");
    Console.WriteLine($"Success: {successCount} matches");
    Console.WriteLine($"Failed: {failureCount} matches");
    Console.WriteLine($"===================================");
}
catch (Exception ex)
{
    Console.WriteLine($"\nFatal Error: {ex.Message}");
    Console.WriteLine($"Stack Trace: {ex.StackTrace}");
}

Console.WriteLine("\nPress any key to exit...");
Console.ReadKey();
